### ISSUE TITLE
About the gaussian_scale_min and gaussian_scale_max Using for other datasets

### ISSUE THREAD

**Issue by ttt-y** [donydchen/mvsplat#98]
Hi, Thanks for your excellent work!

In the `costvolume.yaml` I see the setting
```
gaussian_adapter:
  gaussian_scale_min: 0.5
  gaussian_scale_max: 15.0
  sh_degree: 4
```

I want to know how did you set the gaussian_scale_min and gaussian_scale_max for certain dataset? Thanks!
